In [52]:
class Customer:
    queue=[]
    def __init__(self,name,acc_bal):
        self.name=name
        self.acc_bal=acc_bal
    def add_customer(self):
        self.queue.append(self.name)
    def deposit(self,amount):
        print(f"{self.name} balance after deposit is {self.acc_bal+amount}")
    def withdraw(self,amount):
        print(f"{self.name} balance after withdrawal is {self.acc_bal-amount}")
    def serve_customer(self):
        if self.queue:
            customer=self.queue.pop(0)
            print(f"Served Customer {customer}")
        else:
            print("No customer in queue")
c1=Customer("BHAVYA",5000)
c2=Customer("NEERAJ",6000)
c3=Customer("VIDYA",5000)
c4=Customer("VAKULA",6000)
c5=Customer("HYMA",5000)
c6=Customer("SAKETH",6000)
c1.add_customer()
c2.add_customer()
c3.add_customer()
c4.add_customer()
c5.add_customer()
c6.add_customer()
print("Customers waiting in queue are")
print(c1.queue)
c1.deposit(700)
c1.serve_customer()
c2.withdraw(650)
c2.serve_customer()
print("After serving two customers")
print(c1.queue)
c3.deposit(5000)
c3.serve_customer()
c4.serve_customer()
c5.serve_customer()
c6.serve_customer()
c2.serve_customer()

Customers waiting in queue are
['BHAVYA', 'NEERAJ', 'VIDYA', 'VAKULA', 'HYMA', 'SAKETH']
BHAVYA balance after deposit is 5700
Served Customer BHAVYA
NEERAJ balance after withdrawal is 5350
Served Customer NEERAJ
After serving two customers
['VIDYA', 'VAKULA', 'HYMA', 'SAKETH']
VIDYA balance after deposit is 10000
Served Customer VIDYA
Served Customer VAKULA
Served Customer HYMA
Served Customer SAKETH
No customer in queue


In [54]:
class Node:
    def __init__(self):
        self.mat = [[0] * 6 for _ in range(6)]
    def add(self,x,y):
        self.mat[x][y]=1
    def printmat(self):
        for i in range(6):
            for j in range(6):
                if(self.mat[i][j]==1):
                    print(f"({i}->{j})",end=" ")
            print()
c=Node()
c.add(0,1)
c.add(1,2)
c.add(2,0)
c.add(2,1)
c.add(3,2)
c.add(4,5)
c.add(5,4)
c.printmat()
        
        

(0->1) 
(1->2) 
(2->0) (2->1) 
(3->2) 
(4->5) 
(5->4) 


In [65]:

class Node:
    def __init__(self):
        self.mat = [[0] * 6 for _ in range(6)]
    def add(self,x,y,w):
        self.mat[x][y]=w
    def printmat(self):
        for i in range(6):
            for j in range(6):
                if(self.mat[i][j]>=1):
                    print(f"({i}->{j},{self.mat[i][j]})",end=" ")
            print()
c=Node()
c.add(0,1,6)
c.add(1,2,7)
c.add(2,0,5)
c.add(2,1,4)
c.add(3,2,10)
c.add(4,5,1)
c.add(5,4,3)
c.printmat()
        

(0->1,6) 
(1->2,7) 
(2->0,5) (2->1,4) 
(3->2,10) 
(4->5,1) 
(5->4,3) 


In [ ]:
#q4

In [1]:
class Graph:
    def __init__(self):
        self.graph = {}

    def add_edge(self, u, v, weight):
        if u not in self.graph:
            self.graph[u] = []
        if v not in self.graph:
            self.graph[v] = []
        self.graph[u].append((v, weight))
        self.graph[v].append((u, weight))

    def adjacency_list(self):
        return self.graph

    def adjacency_matrix(self):
        vertices = sorted(self.graph.keys())
        matrix = [[0 for _ in range(len(vertices))] for _ in range(len(vertices))]
        vertex_index = {vertices[i]: i for i in range(len(vertices))}
        for vertex, edges in self.graph.items():
            for edge in edges:
                matrix[vertex_index[vertex]][vertex_index[edge[0]]] = edge[1]
        return matrix


g = Graph()
g.add_edge('A', 'B', 2)
g.add_edge('A', 'C', 3)
g.add_edge('B', 'C', 4)
g.add_edge('B', 'D', 5)
g.add_edge('C', 'D', 1)
g.add_edge('C', 'E', 7)
g.add_edge('D', 'E', 6)

print("Adjacency List:")
print(g.adjacency_list())
print("Adjacency Matrix:")
print(g.adjacency_matrix())

Adjacency List:
{'A': [('B', 2), ('C', 3)], 'B': [('A', 2), ('C', 4), ('D', 5)], 'C': [('A', 3), ('B', 4), ('D', 1), ('E', 7)], 'D': [('B', 5), ('C', 1), ('E', 6)], 'E': [('C', 7), ('D', 6)]}
Adjacency Matrix:
[[0, 2, 3, 0, 0], [2, 0, 4, 5, 0], [3, 4, 0, 1, 7], [0, 5, 1, 0, 6], [0, 0, 7, 6, 0]]


In [15]:
import numpy as np

class Graph:
    def __init__(self, nodes, edges):
        self.nodes = nodes
        self.edges = edges
        self.adj_list = {}
        self.adj_matrix = np.zeros((len(nodes), len(nodes)))
        
        for node in nodes:
            self.adj_list[node] = []
        
        for edge in edges:
            node1, node2, weight = edge
            node1_index = nodes.index(node1)
            node2_index = nodes.index(node2)
            
            self.adj_list[node1].append(node2)
            self.adj_list[node2].append(node1)
            self.adj_matrix[node1_index][node2_index] = weight
            self.adj_matrix[node2_index][node1_index] = weight
            
    def display_adj_list(self):
        for node in self.nodes:
            print("{}: {}".format(node, self.adj_list[node]))
            
    def display_adj_matrix(self):
        print(self.adj_matrix)
        
nodes = ['A', 'B', 'C', 'D', 'E']
edges = [('A', 'B', 1), ('A', 'C', 1), ('A', 'E', 1), ('B', 'C', 1), ('B', 'D', 1), ('C', 'D', 1), ('C', 'E', 1)]

graph = Graph(nodes, edges)

print("Adjacency List:")
graph.display_adj_list()

print("\nAdjacency Matrix:")
graph.display_adj_matrix()

Adjacency List:
A: ['B', 'C', 'E']
B: ['A', 'C', 'D']
C: ['A', 'B', 'D', 'E']
D: ['B', 'C']
E: ['A', 'C']

Adjacency Matrix:
[[0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]
